### ISSUE TITLE
footer: false,页脚貌似不起作用

### ISSUE THREAD

**Issue by quyanyun** [Color-UI/MP-CU#14]
配置文件设置了`footer: false,`页脚并没有去掉

[![TXFO00.png](https://s4.ax1x.com/2022/01/05/TXFO00.png)](https://imgtu.com/i/TXFO00)
[![TXFX7V.png](https://s4.ax1x.com/2022/01/05/TXFX7V.png)](https://imgtu.com/i/TXFX7V)

**Comment by iZaiZaiA** [comment]
已修复

**Comment by quyanyun** [comment]
完美
