### ISSUE TITLE
loading: false不起作用

### ISSUE THREAD

**Issue by quyanyun** [Color-UI/MP-CU#15]
页面js配置了`loading: false`，打开页面还会显示加载中样式...
如图：
[![7kCWuV.png](https://s4.ax1x.com/2022/01/09/7kCWuV.png)](https://imgtu.com/i/7kCWuV)

**Comment by iZaiZaiA** [comment]
![image](https://user-images.githubusercontent.com/26807649/148688538-c2c97e74-6e0a-4cbd-bc4c-2321e069cbaa.png)

![image](https://user-images.githubusercontent.com/26807649/148688552-78556f7d-8a92-48e4-81d3-3e1b75d8d8c3.png)

![image](https://user-images.githubusercontent.com/26807649/148688619-2d54dd17-afb9-4bbb-8792-05ce88ed85d2.png)

![image](https://user-images.githubusercontent.com/26807649/148688632-f87a8ea4-590b-45c7-8b71-5960527f31c7.png)


我测试一下，我这边并没有问题。

**Comment by quyanyun** [comment]
抱歉，是我的我问题，.wxml文件没有写`loading="{{false}}"`
