### ISSUE TITLE
ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。

### ISSUE THREAD

**Issue by CN-HM** [Color-UI/MP-CU#17]
组件：ui-img
调试基础库：2.19.6
问题描述：使用 catchtap="_preview" 导致小程序崩溃，我个人项目尝试解决嵌套点击事件冒泡时出现了这个问题。

**Comment by iZaiZaiA** [comment]
我看看

**Comment by CN-HM** [comment]
对了 手机是一加9pro



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)




 
我看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 对了 手机是一加9pro
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月21日(周五) 晚上9:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17) 我看看 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



我刚刚试了下，没出现小程序崩溃的问题。

![image](https://user-images.githubusercontent.com/26807649/150538794-c9ed7b25-a9da-48d2-9b2a-6bb3f61387c6.png)

**Comment by CN-HM** [comment]
我修改了MP-CU模板做了个DEMO，你在首页点击图片模块，进去后点图片（就是那个win11背景图），然后小程序就会闪退，且可稳定复现。
我的测试机器是一加PRO，真机调试情况下测试的。



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-21 21:54
收件人： Color-UI/MP-CU
抄送： Soup_HM; Author
主题： Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)
对了 手机是一加9pro
…
---原始邮件--- 发件人: @.> 发送时间: 2022年1月21日(周五) 晚上9:50 收件人: @.>; 抄送: @.@.>; 主题: Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17) 我看看 ― Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***>
我刚刚试了下，没出现小程序崩溃的问题。
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 我修改了MP-CU模板做了个DEMO，你在首页点击图片模块，进去后点图片（就是那个win11背景图），然后小程序就会闪退，且可稳定复现。 我的测试机器是一加PRO，真机调试情况下测试的。 


你可以上传下你的demo吗？或者，提供下代码片段。。因为，我这边真机测试，没出现问题，不过，我是小米手机，手上没有一加手机，无法复现问题。

**Comment by CN-HM** [comment]
附件没有收到么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 晚上11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)




  
我修改了MP-CU模板做了个DEMO，你在首页点击图片模块，进去后点图片（就是那个win11背景图），然后小程序就会闪退，且可稳定复现。 我的测试机器是一加PRO，真机调试情况下测试的。
  
你可以上传下你的demo吗？或者，提供下代码片段。。因为，我这边真机测试，没出现问题，不过，我是小米手机，手上没有一加手机，无法复现问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 附件没有收到么

没有

**Comment by CN-HM** [comment]
***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-21 23:24
收件人： Color-UI/MP-CU
抄送： Soup_HM; Author
主题： Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)
附件没有收到么
没有
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
![image](https://user-images.githubusercontent.com/26807649/150555884-3249571d-6ac0-4c06-b1d7-afaaabaa72f5.png)

![image](https://user-images.githubusercontent.com/26807649/150555910-c45d3f53-90a1-4006-86e2-d9ab340a7df2.png)


啥也没有。。。

**Comment by CN-HM** [comment]
留个其他邮箱给我&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)




 

 

 
啥也没有。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
> 留个其他邮箱给我&nbsp;


你直接创建个仓库吧

**Comment by CN-HM** [comment]
https://github.com/CN-HM/MP-CU-Test



***@***.***
 
发件人： ZaiZai
发送时间： 2022-01-22 11:59
收件人： Color-UI/MP-CU
抄送： Soup_HM; Author
主题： Re: [Color-UI/MP-CU] ui-img 这个组件的_preview方法，如果使用catchtap的话会导致小程序崩溃。 (Issue #17)
留个其他邮箱给我 
你直接创建个仓库吧
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iZaiZaiA** [comment]
已更新修复
