### ISSUE TITLE
使用2.21.0以上版本号时，出现错误导致页面白屏。

### ISSUE THREAD

**Issue by CN-HM** [Color-UI/MP-CU#20]
微信从基础库 2.21.2 开始，对获取手机号的接口进行了安全升级，为了使用此功能升级了2.21.3，然后发现报错。

错误提示：WAServiceMainContext.js:2 TypeError: Cannot read property 'push' of undefined
错误位置："/mp-cu/colorUI/components/ui-swiper/ui-swiper“ 64行

**Comment by iZaiZaiA** [comment]
把app.json文件里，

`"lazyCodeLoading": "requiredComponents",`

删了就行

**Comment by CN-HM** [comment]
有效 感谢

**Comment by SteveAndy** [comment]
确实有效！
