### ISSUE TITLE
微信开发者工具Nightly 1.05.2202142之后的版本打开小程序页面样式异常

### ISSUE THREAD

**Issue by SteveAndy** [Color-UI/MP-CU#21]
![image](https://user-images.githubusercontent.com/47137705/156714595-924bc8ae-4f1b-4390-9156-bebb6d8a8b2a.png)

**Comment by iZaiZaiA** [comment]
再 `project.private.config.json` 文件里的 `setting` 节点下，新增 

```
"useCompilerPlugins": [
    "sass"
]
```

即可
