### ISSUE TITLE
不同的页面能修改配置显示不同tabbar吗

### ISSUE THREAD

**Issue by xujin51** [Color-UI/MP-CU#22]
不同的页面能修改配置显示不同tabbar吗

//框架核心配置
import ColorUI from '../mp-cu/main'
export const colorUI = new ColorUI({
    config: {
        theme: 'auto',
        main: 'blue',
        text: 1,
        footer: true,
        share: true,
        shareTitle: 'MP CU（ ColorUI3.x 原生小程序版）',
        homePath: '/pages/home/home',
        tabBar: [{
            title: '文档',
            icon: '/static/tab_icon/document.png',
            curIcon: '/static/tab_icon/document_cur.png',
            url: '/pages/home/home',
            type: 'tab'
        },
        {
            title: '模板',
            icon: '/static/tab_icon/tpl.png',
            curIcon: '/static/tab_icon/tpl_cur.png',
            url: '/pages/template/home',
            type: 'tab'

**Comment by iZaiZaiA** [comment]
暂时还不支持

**Comment by xujin51** [comment]
希望完善一下  内置 store 用法  不是很了解

内置 store [使用方法参考](https://github.com/Color-UI/MP-CU#ColorUi.store)

**Comment by iZaiZaiA** [comment]
如果你用过 类似vuex这种状态管理的话，很容易就理解了。如果你没用过类似vuex这种状态管理的话，可以先去了解了解一下vuex相关的用法，就会明白了。
