### ISSUE TITLE
modal 模态框遮罩层无法覆盖input输入框

### ISSUE THREAD

**Issue by feihongxiansen** [Color-UI/MP-CU#30]
modal弹出层，下面有input输入框时，点击会被穿透，input的文字内容会显示在模态框之上，并且还会获取光标焦点到input框，查了下资料，说是input有原生界面，层级最高，无法通过view的z-index来覆盖原生界面层级

**Comment by iZaiZaiA** [comment]
原生组件同层渲染
同层渲染是为了解决原生组件的层级问题，在支持同层渲染后，原生组件与其它组件可以随意叠加，有关层级的限制将不再存在。但需要注意的是，组件内部仍由原生渲染，样式一般还是对原生组件内部无效。当前所有原生组件（除 input 组件 focus 状态）均已支持同层渲染。

原生组件的使用限制
除事件相关，同层渲染下已无以下限制

由于原生组件脱离在 WebView 渲染流程外，因此在使用时有以下限制：

原生组件的层级是最高的，所以页面中的其他组件无论设置 z-index 为多少，都无法盖在原生组件上。
后插入的原生组件可以覆盖之前的原生组件。
原生组件还无法在 [picker-view](https://developers.weixin.qq.com/miniprogram/dev/component/picker-view.html) 中使用。
基础库 2.4.4 以下版本，原生组件不支持在 [scroll-view](https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html)、[swiper](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html)、[movable-view](https://developers.weixin.qq.com/miniprogram/dev/component/movable-view.html) 中使用。
部分 CSS 样式无法应用于原生组件，例如：
无法对原生组件设置 CSS 动画
无法定义原生组件为 position: fixed
不能在父级节点使用 overflow: hidden 来裁剪原生组件的显示区域
原生组件的事件监听不能使用 bind:eventname 的写法，只支持 bindeventname。原生组件也不支持 catch 和 capture 的事件绑定方式。
原生组件会遮挡 vConsole 弹出的调试面板。
在工具上，原生组件是用 web 组件模拟的，因此很多情况并不能很好的还原真机的表现，建议开发者在使用到原生组件时尽量在真机上进行调试。

cover-view 与 cover-image
为了解决原生组件层级最高的限制。小程序专门提供了 [cover-view](https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html) 和 [cover-image](https://developers.weixin.qq.com/miniprogram/dev/component/cover-image.html) 组件，可以覆盖在部分原生组件上面。这两个组件也是原生组件，但是使用限制与其他原生组件有所不同。

原生组件相对层级
同层渲染下已无以下问题

为了可以调整原生组件之间的相对层级位置，小程序在 v2.7.0 及以上版本支持在样式中声明 z-index 来指定原生组件的层级。该 z-index 仅调整原生组件之间的层级顺序，其层级仍高于其他非原生组件。
