### ISSUE TITLE
导航栏

### ISSUE THREAD

**Issue by XiaokangLei** [Color-UI/MP-CU#8]
你好，我在使用导航栏的时候，在任何页面都会返回到home页面，如何解决呢。

**Comment by iZaiZaiA** [comment]
你用的是<ui-sys>组件内导航栏，还是<ui-navbar>的导航栏呢，如果是<ui-navbar>的导航栏，可以先启用 `stopBack` 属性，然后通过 bind:navback="navback" 事件，手动处理一下，因为内置的返回有点问题，后续文档写完后会修复。

**Comment by bypanghu** [comment]
> 
首先要确定你是不是存在tabbar ，然后才能判断你的返回状态

**Comment by bypanghu** [comment]
> 你好，我在使用导航栏的时候，在任何页面都会返回到home页面，如何解决呢。

我们返回的处理方式是先通过 ` getCurrentPages ` 这个方法去获得你现在所处是不是第一层（每次进入tabbar 就会重置 ），如果是第一个就会自动 `switchTab`你上次的tabbar的`path`，不是第一个就会走返回页面，当然，如果你需要用原生的tabbar，可能就需要自己处理返回函数了，或者在tabbar 页面运行 
```javascript
this.setState({
      sys_home_page : ${path}
  })
```
将当前的tabbar 告诉 CU MP的处理单元。

**Comment by XiaokangLei** [comment]
> 你用的是 `<ui-sys>` 组件内导航栏，还是 `<ui-navbar>` 的导航栏呢，如果是 `<ui-navbar>` 的导航栏，可以先启用 `stopBack` 属性，然后通过 `bind:navback="navback"` 事件，手动处理一下，因为内置的返回有点问题，后续文档写完后会修复。

感谢，我用的都是<ui-sys>组件内导航，我用<ui-navbar>试一下

**Comment by XiaokangLei** [comment]
> > 你好，我在使用导航栏的时候，在任何页面都会返回到home页面，如何解决呢。
> 
> 我们返回的处理方式是先通过 `getCurrentPages` 这个方法去获得你现在所处是不是第一层（每次进入tabbar 就会重置 ），如果是第一个就会自动 `switchTab`你上次的tabbar的`path`，不是第一个就会走返回页面，当然，如果你需要用原生的tabbar，可能就需要自己处理返回函数了，或者在tabbar 页面运行
> 
> ```js
> this.setState({
>       sys_home_page : ${path}
>   })
> ```
> 
> 将当前的tabbar 告诉 CU MP的处理单元。

感谢，我试一下，目前用的都是`<ui-sys>`

**Comment by iZaiZaiA** [comment]
> > > 你好，我在使用导航栏的时候，在任何页面都会返回到home页面，如何解决呢。
> > 
> > 
> > 我们返回的处理方式是先通过 `getCurrentPages` 这个方法去获得你现在所处是不是第一层（每次进入tabbar 就会重置 ），如果是第一个就会自动 `switchTab`你上次的tabbar的`path`，不是第一个就会走返回页面，当然，如果你需要用原生的tabbar，可能就需要自己处理返回函数了，或者在tabbar 页面运行
> > ```js
> > this.setState({
> >       sys_home_page : ${path}
> >   })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将当前的tabbar 告诉 CU MP的处理单元。
> 
> 感谢，我试一下，目前用的都是`<ui-sys>`


v3.2.8已修复，刚提交代码，可以拉取下

**Comment by XiaokangLei** [comment]
> > > > 你好，我在使用导航栏的时候，在任何页面都会返回到home页面，如何解决呢。
> > > 
> > > 
> > > 我们返回的处理方式是先通过 `getCurrentPages` 这个方法去获得你现在所处是不是第一层（每次进入tabbar 就会重置 ），如果是第一个就会自动 `switchTab`你上次的tabbar的`path`，不是第一个就会走返回页面，当然，如果你需要用原生的tabbar，可能就需要自己处理返回函数了，或者在tabbar 页面运行
> > > ```js
> > > this.setState({
> > >       sys_home_page : ${path}
> > >   })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 将当前的tabbar 告诉 CU MP的处理单元。
> > 
> > 
> > 感谢，我试一下，目前用的都是`<ui-sys>`
> 
> v3.2.8已修复，刚提交代码，可以拉取下

感谢！这速度杠杠的
