### ISSUE TITLE
<ui-swiper>问题

### ISSUE THREAD

**Issue by XiaokangLei** [Color-UI/MP-CU#9]
您好，`<ui-swiper>`如何增加跳转页面呢？目前我是在ui-swiper.js的`toTap()`函数中增加跳转代码`wx.navigateTo({url: e.currentTarget.dataset.item.url })`，直接改动组件显然是不合理的，请问该如何操作实现`<ui-swiper>`跳转页面呢？

**Comment by iZaiZaiA** [comment]
> 您好，`<ui-swiper>`如何增加跳转页面呢？目前我是在ui-swiper.js的`toTap()`函数中增加跳转代码`wx.navigateTo({url: e.currentTarget.dataset.item.url })`，直接改动组件显然是不合理的，请问该如何操作实现`<ui-swiper>`跳转页面呢？

您好，非常抱歉，暂时还不支持设置跳转或返回点击事情，今天晚上我完善下，完善后，我会回复您。

**Comment by iZaiZaiA** [comment]
> 您好，`<ui-swiper>`如何增加跳转页面呢？目前我是在ui-swiper.js的`toTap()`函数中增加跳转代码`wx.navigateTo({url: e.currentTarget.dataset.item.url })`，直接改动组件显然是不合理的，请问该如何操作实现`<ui-swiper>`跳转页面呢？

您好，已经修复了。

使用方式如下：

```JavaScript
//type: switchTab/reLaunch/redirectTo/navigateTo/eve
swiperList: [
      {
          img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg',
          url: '/pages/document/system/system',
          type: 'navigateTo' //直接跳转类型
      },
      {
          img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big37006.jpg',
          url: '/pages/custom/home',
          type: 'switchTab' //直接跳转类型
      },
      {
          img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big39000.jpg',
          type: 'eve' //事件方式
      },
      {
          img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big10001.jpg',
          type: 'eve'
      },
]
```

加事件

```html
<ui-swiper info="{{swiperList}}" dotCur="ui-BG-Main" bind:uiTap="swiperTap"/>
```

注意type: switchTab/reLaunch/redirectTo/navigateTo/eve

类型为eve时，为点击事件，不会跳转，其它类型会跳转。

**Comment by XiaokangLei** [comment]
> > 您好，`<ui-swiper>`如何增加跳转页面呢？目前我是在ui-swiper.js的`toTap()`函数中增加跳转代码`wx.navigateTo({url: e.currentTarget.dataset.item.url })`，直接改动组件显然是不合理的，请问该如何操作实现`<ui-swiper>`跳转页面呢？
> 
> 您好，已经修复了。
> 
> 使用方式如下：
> 
> ```js
> //type: switchTab/reLaunch/redirectTo/navigateTo/eve
> swiperList: [
>       {
>           img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg',
>           url: '/pages/document/system/system',
>           type: 'navigateTo' //直接跳转类型
>       },
>       {
>           img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big37006.jpg',
>           url: '/pages/custom/home',
>           type: 'switchTab' //直接跳转类型
>       },
>       {
>           img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big39000.jpg',
>           type: 'eve' //事件方式
>       },
>       {
>           img: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big10001.jpg',
>           type: 'eve'
>       },
> ]
> ```
> 
> 加事件
> 
> ```
> <ui-swiper info="{{swiperList}}" dotCur="ui-BG-Main" bind:uiTap="swiperTap"/>
> ```
> 
> 注意type: switchTab/reLaunch/redirectTo/navigateTo/eve
> 
> 类型为eve时，为点击事件，不会跳转，其它类型会跳转。

感谢，我试一下

**Comment by iZaiZaiA** [comment]
-----
